./bin/Release/main: 
	g++.exe -Wall -Wno-unused-function -O2 -Wall -std=c++11 -Iinclude -c C:\Users\Bruno\Desktop\UFRGS\Semestre6\FCG\lab1\Laboratorio_1_Codigo_Fonte\src\main.cpp -o obj\Release\src\main.o
	g++.exe -Llib -o bin\Release\main.exe obj\Release\src\glad.o obj\Release\src\main.o  lib\libglfw3.a -lgdi32 -lopengl32 -s lib-mingw-32\libglfw3.a -lgdi32 -lopengl32
	

